dist: xenial
language: python
python:
  - 3.6

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - tox -e coverage,codecov,package

credentials:
  - &pypi
    provider: pypi
    user: zsimic
    password:
      secure: "KQlK7VkxBZsexEHwhutDIBZCin/k5fLtf2Oa3Z7ITewghWw1OzHZ6QQOukPMPQJ64+6W2ryL/6JesRXxTJNnoCdK6/JeFj9mnXChbAX5wmtDNw5gL4UmbCL8q2p53Y5ZlT/MAmBLudcL4TnHdxK2UN1nibURXnmELM7hSQpRg+R5qzUA/seIz+bRTbDr0YnEUGcv0ojDmenuwxT3n6YQOjt4cDXu8+GqLiSwAzTi41gcmQmAyiOpZZMztpD9gpqO7gyhB0N/U0xqSOLp8oNJfTFP7b+MCuqECvRHEGDXfZ8Z1SA5ZYhRvOucroQwhV8XDvn/A2GQdZW7rakTtwhgTPPjj/4497Q1KOAmluTjW7BTtDiX32ewsTQ2I7mLMX1k7oKPMVNk8/VLb4r3U+RLj2a5ls7dEEzF4/PnJapiSTyzqbrbZpgCA8GxJXBtQIF+Ur6QlUtGCwJyYf3rFTgViwgbAsMGTvYuL17899fDYQyuURnOmG5gvU9Jb+lWv2utzd6h1LheL5h7e5Q96OOBhzipS8/pGJixgNcH3CstTrW1kIvhp2RavV035mVP16XFP39DSrUYpYn6DS5uv3HVKaR2LUJFlA23Psvw8YTMM2V1KdHtbVwDE27SwCLHed/Q8JaWuXeQxlOZEy6t2WnUOHg8WJzu2wm1n3nQoQiHjjg="
  - &github
    provider: releases
    api_key:
      secure: xNA2S0u/CvEmhBf2WwHONVUM2H/SV3KX31TA9JfI/DCpiFKxohQBIt27hU0cp7uPeVe3Zi5X5V52VZgDJQiuGb0DYh8tLF9qoP5jIvOHw4xd5SiC6ohePtm62IIyaa6zeVtWgOMII5kvuCJV7KiJHsare+r/yVru3JdPRDoIBtFLvlmj13lEgUBEnV/4mALzCkWtZ2W99H98K6pzgVuZThGkuy5GOL9xlrDvHkyKao+aOJDORYW5IefD+Jz9lrb+ahn4dwcH3Kv/UTyim5ahdjqrSekVSAG0Z0I9mbeNXyCLYjqEpzQwWJHzxDeDdbLFr7mFevrLzs+/+DSP59y1oRDLe2cBYDaGNIJ+9OnZDyCp3UJRUemjm3isN0jp1M8Fahtzb4ffAe8S598C5c+shWmpA2TLWjKMrLA49BSg1HHE+cgXdTIF0LYCikRmG0IFdkLDxGqYD75qkCSPa1GZSMcLGdqy7BUHYfc+/GdWdYECu+jI2/37+ez+oSFb66xYANLVqf9SgWBnO+METrkeu8hbprHSU6NgrFUxoqOQWEU+lBshTzOHn58M1O1tYfHXXv600JgQTjLlf5xGpV3ZzBKhKKGKwzkC+7csue6a9kDs+PNFqbRsd1b+YWuupJ88HCCcun7OVVq2nb5esFQ8hNlIGcwxOWPdSQ6/14KUzgs=


deploy:
  - <<: *pypi
    distributions: "sdist bdist_wheel --universal"
    on:
      python: 3.6
      repo: zsimic/pickley
      tags: true
    skip_cleanup: true
  - <<: *github
    file: ".tox/package/dist/pickley"
    on:
      repo: zsimic/pickley
      tags: true
    skip_cleanup: true
